### ISSUE TITLE
Run from the file's directory

### ISSUE THREAD

**Issue by cblp** [vigoo/stylish-haskell-vscode#6]
`stylish` reads its configuration from the current directory (or higher), so you must run it with proper working directory.

Running from project directory may be right solution if Code were supported multiple project windows. But currently it doesn't, and many people open a _projects_ directory that is higher than any project directory.

So the only solution I see is to run `stylish` from the file's own directory.

Currently `stylish` is run from nowhere, so it is unable to use project config. I consider it a bug.

**Comment by cblp** [comment]
I want to implement this myself. How can I test your package?

**Comment by vigoo** [comment]
Hi, thanks for the report. Unfortunately there are no ways to automatically test it currently, I just did it manually (running it from vscode, opening a haskell project..).

If you don't want to bother with it I'll probably have time to do it in the next few days.

**Comment by cblp** [comment]
I just noticed some files in `test` directory and tried `npm test` without result.

Ok, thank you.

**Comment by cblp** [comment]
How can I help?

**Comment by cblp** [comment]
thanks!

**Comment by vigoo** [comment]
I'll upload the new version soon
