### ISSUE TITLE
Output pane steals focus

### ISSUE THREAD

**Issue by cblp** [vigoo/stylish-haskell-vscode#7]
On syntax error in my code, Output pane arises with Stylish error message. The focus is there, and I have to use mouse to return to editing and fix the error.

I suggest to use Errors pane to show errors from Stylish.

**Comment by vigoo** [comment]
You can now turn off the output pane with the `stylishHaskell.showConsoleOnError` option, and it will always use vscode's diagnostics provider to show the error (if it has an `SrcLoc` part)
