### ISSUE TITLE
Cursor resets to the end of file

### ISSUE THREAD

**Issue by cblp** [vigoo/stylish-haskell-vscode#9]

**Comment by cblp** [comment]
I think this happens because the whole file is replaced.

**Comment by keremispirli** [comment]
According to this comment:
https://github.com/Microsoft/vscode/issues/47382#issuecomment-381138434
the reason may be "extension is pushing edits directly on the buffer, avoiding going through the formatter" and "best practice is to register a formatter if [extensions] provide formatting".

Looks like it got broken with latest changes in VS Code.
